### ISSUE TITLE
Provide a better handling of clients disconnections

### ISSUE THREAD

**Issue by rickdesantis** [SINTEF-9012/cloudml#37]
I'm using CloudML using the WebSocket interface. Whenever I start a daemon with

```java
org.cloudml.websocket.Daemon.main(new String[] { "9000" });
```

if I connect to it, then disconnect from it and reconnect again, every-time something happens the daemon will throw a

```java
org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:566)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:543)
	at org.cloudml.websocket.WsPeerStub.sendMessage(WsPeerStub.java:59)
	at org.cloudml.mrt.NodificationCentre.checkAndNotify(NodificationCentre.java:54)
	at org.cloudml.mrt.NodificationCentre$1.run(NodificationCentre.java:88)
```

as if the previous instance wasn't correctly disconnected, even when using the `closeBlocking()` method of the `WebSocketClient` class (thus disconnecting correctly from the server). Also the message

```
/127.0.0.1:60326 left.
```

was shown, so the server knows that I disconnected from it.

Did I forget anything? Is there a cleaner way for disconnecting?

**Comment by nicolasferry** [comment]
I did some updates, it should be better now.
