### ISSUE TITLE
[UI:shell] Exception when trying to store model with puppet resources

### ISSUE THREAD

**Issue by boc-modaclouds** [SINTEF-9012/cloudml#50]
Hi Nicolas,

when loading a model containing PuppetResources from a file and trying to store it back to another file I get the following exception:

CloudML > load deployment from AGU_1.json
Info: Will wait until completion
Info: Loading Complete.

CloudML > store deployment in x.json
line 1:17 mismatched input 'in' expecting 'to'
Info: Will wait until completion
[Ljava.lang.StackTraceElement;@ad6f5f2
2015-09-21 07:33:03 net.cloudml.core.impl.ResourceImpl cannot be cast to net.cloudml.core.PuppetResource
java.lang.ClassCastException: net.cloudml.core.impl.ResourceImpl cannot be cast to net.cloudml.core.PuppetResource
        at org.cloudml.codecs.BridgeToKmf.convertResources(BridgeToKmf.java:117)
        at org.cloudml.codecs.BridgeToKmf.internalComponentToKmf(BridgeToKmf.java:325)
        at org.cloudml.codecs.BridgeToKmf.internalComponentsToKmf(BridgeToKmf.java:280)
        at org.cloudml.codecs.BridgeToKmf.toKMF(BridgeToKmf.java:74)
        at org.cloudml.codecs.KMFBridge.toKMF(KMFBridge.java:52)
        at org.cloudml.codecs.JsonCodec.save(JsonCodec.java:86)
        at org.cloudml.facade.Facade.handle(Facade.java:499)
        at org.cloudml.facade.commands.StoreDeployment.execute(StoreDeployment.java:45)
        at org.cloudml.facade.Execution.run(Execution.java:75)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Error: Error while saving model: java.lang.ClassCastException: net.cloudml.core.impl.ResourceImpl cannot be cast to net.cloudml.core.PuppetResource

Br,
Stepan

**Comment by nicolasferry** [comment]
Hi Stepan,

I updated the serialization code and I did some tests, it should work fine now.

Cheers,
Nicolas

**Comment by boc-modaclouds** [comment]
Confirmed - works with latest version from github.

Thx,
Stepan
